### ISSUE TITLE
"The love font is huge"

### ISSUE THREAD

**Issue by quietly-turning** [Simply-Love/Simply-Love-SM5#112]
> The love font is huge and I can't like the others lol
>At 0% mini the judgement font is bigger than normal (stock itg) 

![31948340_10102347195568074_988630428485156864_n](https://user-images.githubusercontent.com/1253483/39718328-f4ace728-5203-11e8-9453-bc5f2bf9db18.png)

My rudimentary analysis in Photoshop is shown above, with SM5 on the left and OpenITG on the right.  If anyone else can shine more light on this, I can look into it further.

**Comment by dguzek** [comment]
A more precise analysis reveals that nearly every visual aspect of ScreenGameplay is, in fact, slightly different than the 3.95 counterpart.  In this screencap, SM3.95 is on the left and SM5 is on the right.

<img width="1440" alt="comparison" src="https://user-images.githubusercontent.com/1253483/39732879-d1245f68-523d-11e8-9ce1-5d36eb04943a.png">

Things I can discern:

- LifeMeter is longer in SM3.95
- Song Progress Meter is longer in SM5
- LifeMeter and Song Progress Meter have more height in SM5
- BPM text is zoomed more in SM3.95
- PercentScore has more height in SM3.95
- Combo is translated farther down the screen in SM5
