### ISSUE TITLE
If you're in ECFA mode, "disable decents and wayoffs" actually disables greats and decents.

### ISSUE THREAD

**Issue by ianklatzco** [Simply-Love/Simply-Love-SM5#139]
![image](https://user-images.githubusercontent.com/1487413/48462427-cbcea780-e79d-11e8-814a-a338dd4221f0.png)

**Comment by ianklatzco** [comment]
Here's the relevant code. Looks a little tricky to implement, since it'll require taking care of the language files too.

https://github.com/dguzek/Simply-Love-SM5/blob/7e53185023cff9f8f8fdb9409568db2ff3a94cc2/Scripts/SL-PlayerOptions.lua#L319

**Comment by ianklatzco** [comment]
This is a good freshman project, so I'll check to see if any of them are interested in giving it a stab.

**Comment by andrewipark** [comment]
With 3d62425 it is now possible to get the OptionsRow to dynamically change the displayed option strongs, but still have them map to the same choices engine side. Unfortunately, this does not apply to the (promptly localized) name of the OptionRow.

I wonder if binding (yet another, ugh) property in the table for a given OptionRow will work:
```lua
-- in a given OptionRow
name = function() return "do stuff here" end
-- insert this into OptionRowDefault to replace line ~452
if Overrides[name].NameFunction then
    self.name = Overrides[name].NameFunction()
else self.name = name end
```

**Comment by natano** [comment]
I just verified that in FA+ mode the name of modifiers are consistent with gameplay behaviour now.
Closing this issue now as the bug appears to have been fixed in the meantime.
